baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

# Settings for relearn theme
[params]
themeVariant = "jasmin"

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"

[[menu.shortcuts]]
name = "<i class='fas fa-list'></i> Categories"
url = "/categories"